# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_extras',
            name='Fecha_calculo',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
