# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_recomendaciones_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendaciones_config',
            new_name='Recomendadores_config',
        ),
        migrations.AlterModelTable(
            name='recomendadores_config',
            table='recomendadores_config',
        ),
    ]
