# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160412_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listas_recomendadores_config',
        ),
    ]
