# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_producto', models.IntegerField()),
                ('comentario', models.TextField(max_length=1000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Categoria', models.CharField(max_length=255)),
                ('Latitud', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
                ('Colonia', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Alias', models.CharField(max_length=255)),
                ('Longitud', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CP', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=255)),
                ('Municipio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('CP', models.CharField(max_length=255)),
                ('Genero', models.CharField(max_length=255)),
                ('Apellido_p', models.CharField(max_length=255)),
                ('Apellido_m', models.CharField(max_length=255)),
                ('Ciudad', models.CharField(max_length=255)),
                ('Hijos', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Estado_civil', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
                ('Nacimiento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Users'),
        ),
    ]
