# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Users'),
        ),
    ]
