# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=255)),
                ('Latitud', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
                ('Colonia', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Alias', models.CharField(max_length=255)),
                ('Longitud', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=255)),
                ('Descripcion', models.CharField(max_length=255)),
                ('CP', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=255)),
                ('Municipio', models.CharField(max_length=255)),
                ('id_producto', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genero', models.CharField(max_length=255)),
                ('Nacimiento', models.CharField(max_length=255)),
                ('Apellido_p', models.CharField(max_length=255)),
                ('Apellido_m', models.CharField(max_length=255)),
                ('Ciudad', models.CharField(max_length=255)),
                ('Hijos', models.CharField(max_length=255)),
                ('Estado_civil', models.CharField(max_length=255)),
                ('Nombre', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
                ('CP', models.CharField(max_length=255)),
                ('id_usuario', models.IntegerField(max_length=11)),
            ],
        ),
    ]
