# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_calificable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_extras',
            fields=[
                ('Imagen_fuente', models.CharField(max_length=255)),
                ('Calificacion', models.FloatField()),
                ('Precio', models.FloatField()),
                ('Descuento', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_extras',
            },
        ),
    ]
